let arrayEquipos = [
    {
        id: 0,
        nombre_equipo: 'Central Larroque',
        nombre_equipo_short: 'CCL',
        escudo_equipo: './assets/escudos/CCL.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 1,
        nombre_equipo: 'Central Larroque',
        nombre_equipo_short: 'CCL',
        escudo_equipo: './assets/escudos/CCL.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 2,
        nombre_equipo: 'La Vencedora',
        nombre_equipo_short: 'VEN',
        escudo_equipo: './assets/escudos/lavencedora.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 3,
        nombre_equipo: 'La Vencedora',
        nombre_equipo_short: 'VEN',
        escudo_equipo: './assets/escudos/lavencedora.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 4,
        nombre_equipo: 'Black River',
        nombre_equipo_short: 'RIV',
        escudo_equipo: './assets/escudos/blackriver.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 5,
        nombre_equipo: 'Black River',
        nombre_equipo_short: 'RIV',
        escudo_equipo: './assets/escudos/blackriver.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 6,
        nombre_equipo: 'Pueblo Nuevo',
        nombre_equipo_short: 'PN',
        escudo_equipo: './assets/escudos/pueblonuevo.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 7,
        nombre_equipo: 'Pueblo Nuevo',
        nombre_equipo_short: 'PN',
        escudo_equipo: './assets/escudos/pueblonuevo.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 8,
        nombre_equipo: 'Deportivo Urdinarrain',
        nombre_equipo_short: 'CDU',
        escudo_equipo: './assets/escudos/deportivo_urd.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 9,
        nombre_equipo: 'Deportivo Urdinarrain',
        nombre_equipo_short: 'CDU',
        escudo_equipo: './assets/escudos/deportivo_urd.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 10,
        nombre_equipo: 'Juventud Urdinarrain',
        nombre_equipo_short: 'JUV(U)',
        escudo_equipo: './assets/escudos/juv_urd.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 11,
        nombre_equipo: 'Juventud Urdinarrain',
        nombre_equipo_short: 'JUV(U)',
        escudo_equipo: './assets/escudos/juv_urd.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 12,
        nombre_equipo: 'Juventud Unida',
        nombre_equipo_short: 'JUV(G)',
        escudo_equipo: './assets/escudos/juv_unida_gchu.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 13,
        nombre_equipo: 'Juventud Unida',
        nombre_equipo_short: 'JUV(G)',
        escudo_equipo: './assets/escudos/juv_unida_gchu.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 14,
        nombre_equipo: 'Central Entrerriano',
        nombre_equipo_short: 'CCE',
        escudo_equipo: './assets/escudos/central_entrerriano.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 15,
        nombre_equipo: 'Central Entrerriano',
        nombre_equipo_short: 'CCE',
        escudo_equipo: './assets/escudos/central_entrerriano.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 16,
        nombre_equipo: 'Sud America',
        nombre_equipo_short: 'SUD',
        escudo_equipo: './assets/escudos/sudamerica.svg',
        division: 'a',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 17,
        nombre_equipo: 'Sud America',
        nombre_equipo_short: 'SUD',
        escudo_equipo: './assets/escudos/sudamerica.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 18,
        nombre_equipo: 'Sarmiento',
        nombre_equipo_short: 'SAR',
        escudo_equipo: './assets/escudos/SAR.svg',
        division: 'a',
        pts: 0,
        categoria: 'primera',
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 19,
        nombre_equipo: 'Sarmiento',
        nombre_equipo_short: 'SAR',
        escudo_equipo: './assets/escudos/SAR.svg',
        division: 'a',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 20,
        nombre_equipo: 'Defensores del Oeste',
        nombre_equipo_short: 'DEF',
        escudo_equipo: './assets/escudos/def_oeste.svg',
        division: 'a',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 21,
        nombre_equipo: 'Defensores del Oeste',
        nombre_equipo_short: 'DEF',
        escudo_equipo: './assets/escudos/def_oeste.svg',
        division: 'a',
        categoria:'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 22,
        nombre_equipo: 'Cerro Porteño',
        nombre_equipo_short: 'CP',
        escudo_equipo: './assets/escudos/cerro.svg',
        division: 'b',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 23,
        nombre_equipo: 'Cerro Porteño',
        nombre_equipo_short: 'CP',
        escudo_equipo: './assets/escudos/cerro.svg',
        division: 'b',
        categoria:'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 24,
        nombre_equipo: 'Union',
        nombre_equipo_short: 'UNI',
        escudo_equipo: './assets/escudos/union.svg',
        division: 'b',
        categoria:'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 25,
        nombre_equipo: 'Union',
        nombre_equipo_short: 'UNI',
        escudo_equipo: './assets/escudos/union.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 26,
        nombre_equipo: 'La Ribera',
        nombre_equipo_short: 'RIB',
        escudo_equipo: './assets/escudos/laribera.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 27,
        nombre_equipo: 'La Ribera',
        nombre_equipo_short: 'RIB',
        escudo_equipo: './assets/escudos/laribera.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 28,
        nombre_equipo: 'Sporting',
        nombre_equipo_short: 'SPO',
        escudo_equipo: './assets/escudos/sporting.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 29,
        nombre_equipo: 'Sporting',
        nombre_equipo_short: 'SPO',
        escudo_equipo: './assets/escudos/sporting.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 30,
        nombre_equipo: 'Juvenil del Norte',
        nombre_equipo_short: 'JDN',
        escudo_equipo: './assets/escudos/juvenil.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 31,
        nombre_equipo: 'Juvenil del Norte',
        nombre_equipo_short: 'JDN',
        escudo_equipo: './assets/escudos/juvenil.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 32,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: './assets/escudos/gurises.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 33,
        nombre_equipo: 'Deportivo Gurises',
        nombre_equipo_short: 'GUR',
        escudo_equipo: './assets/escudos/gurises.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 34,
        nombre_equipo: 'Independiente',
        nombre_equipo_short: 'CAI',
        escudo_equipo: './assets/escudos/independiente.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 35,
        nombre_equipo: 'Independiente',
        nombre_equipo_short: 'CAI',
        escudo_equipo: './assets/escudos/independiente.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 36,
        nombre_equipo: 'Sportivo Larroque',
        nombre_equipo_short: 'CSL',
        escudo_equipo: './assets/escudos/sportivo_larroque.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 37,
        nombre_equipo: 'Sportivo Larroque',
        nombre_equipo_short: 'CSL',
        escudo_equipo: './assets/escudos/sportivo_larroque.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 38,
        nombre_equipo: 'Camioneros',
        nombre_equipo_short: 'CAM',
        escudo_equipo: './assets/escudos/camioneros.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 39,
        nombre_equipo: 'Camioneros',
        nombre_equipo_short: 'CAM',
        escudo_equipo: './assets/escudos/camioneros.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 40,
        nombre_equipo: 'Isleños Independientes',
        nombre_equipo_short: 'ISL',
        escudo_equipo: './assets/escudos/islenios.svg',
        division: 'b',
        categoria: 'primera',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
    {
        id: 41,
        nombre_equipo: 'Isleños Independientes',
        nombre_equipo_short: 'ISL',
        escudo_equipo: './assets/escudos/islenios.svg',
        division: 'b',
        categoria: 'sub',
        pts: 0,
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
    },
];